# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_data.proto

require 'google/protobuf'


descriptor_data = "\n\x0ftest_data.proto\"\xd5\x02\n\x04\x44\x61ta\x12\x11\n\tbool_test\x18\x01 \x01(\x08\x12\x11\n\tdate_test\x18\x02 \x01(\x05\x12\x15\n\rdatetime_test\x18\x03 \x01(\t\x12\x12\n\nfloat_test\x18\x04 \x01(\x01\x12\x16\n\x0egeography_test\x18\x05 \x01(\t\x12\x14\n\x0cinteger_test\x18\x06 \x01(\x03\x12\x11\n\tjson_test\x18\x07 \x01(\t\x12\x14\n\x0cnumeric_test\x18\x08 \x01(\x03\x12\x13\n\x0bstring_test\x18\t \x01(\t\x12\x11\n\ttime_test\x18\n \x01(\t\x12\x16\n\x0etimestamp_test\x18\x0b \x01(\x03\x12\x1b\n\x13repeated_field_test\x18\x0c \x03(\x03\x12!\n\x0brecord_test\x18\r \x01(\x0b\x32\x0c.Data.Record\x1a%\n\x06Record\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Data").msgclass
Data::Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Data.Record").msgclass
